import type { DeviceData } from '../pages/Inventory/DeviceInventory';

const dummyDeviceData: DeviceData[] = [
  {
    device_details_id: '1',
    device_id: 'D001',
    screen_id: 'S001',
    device_name: 'Device A',
    main_category_name: 'Category 1',
    category_name: 'Subcategory 1',
    sub_category_name: 'Subcategory A',
    location_type: 'Indoor',
    screen_location: 'Lobby',
    latitude: '37.7749',
    longitude: '-122.4194',
    screen_size: '42 inches',
    resolution: '1920x1080',
    aspect_ratio: '16:9',
    monthly_footfall: '10000',
    state: 'California',
    city: 'San Francisco',
    country: 'USA',
    on_field_screen_count: '5',
    monday_start_time: '08:00',
    monday_end_time: '20:00',
    tuesday_start_time: '08:00',
    tuesday_end_time: '20:00',
    wednesday_start_time: '08:00',
    wednesday_end_time: '20:00',
    thursday_start_time: '08:00',
    thursday_end_time: '20:00',
    friday_start_time: '08:00',
    friday_end_time: '20:00',
    saturday_start_time: '10:00',
    saturday_end_time: '18:00',
    sunday_start_time: '10:00',
    sunday_end_time: '18:00',
    daily_impression: '5000',
    cost_for_impression: '0.05',
    cpi_cost: '250',
    min_operating_price: '1000',
    loop_timing: '60 seconds',
    slot_timing: '30 seconds',
    slot_details: '10 slots per hour',
    slot_per_month: '300',
    daily_hours_of_loop: '12',
    cost_per_spot: '50',
    cost_per_audience_imp: '0.01',
    status: 'Active',
    default_date: '2026-03-17',
    update_date: '2026-03-17',
    email_id: 'manager@example.com',
    first_name: 'John',
    last_name: 'Doe',
    admin_flag: 'true',
    company_name: 'TechCorp',
    user_password: 'password123',
    device_limit: '10',
    expiry_date: '2026-12-31',
    manager_name: 'Jane Smith',
    access_type: 'Full',
    markup_applicable: 'Yes',
    code: 'DEV001',
    old_device_image: 'https://example.com/old-image.jpg',
    device_image: 'https://example.com/device-image.jpg',
  },
  // Add more dummy entries as needed
];

export default dummyDeviceData;