/**
 * Relative path segments for nested routes under the app layout (`/`).
 * Use these in `<Route path={...} />` definitions.
 */
export const ROUTE_SEGMENTS = {
  DASHBOARD: 'dashboard',
  DASHBOARD_SALES: 'dashboard/sales',
  DASHBOARD_PLANNER: 'dashboard/planner',
  COURSES: 'courses',
  NOTIFICATIONS: 'notifications',
  PROFILE: 'profile',
  GMAIL: 'gmail',
  GMAIL_SEND: 'gmail/send',
  GMAIL_RECEIVE: 'gmail/receive',
  LEAD_SOURCE: 'lead-source',
  INVENTORY_DEVICE: 'inventory/device',
  MEETING_SCHEDULE: 'meeting-schedule',
  LEAD_MANAGEMENT: 'lead-management',
  LEAD_MANAGEMENT_ALL: 'lead-management/all-leads',
  LEAD_MANAGEMENT_BRIEF: 'lead-management/brief-leads',
  LEAD_MANAGEMENT_PENDING: 'lead-management/pending',
  LEAD_MANAGEMENT_INTERESTED: 'lead-management/interested',
  LEAD_MANAGEMENT_MEETING_SCHEDULED: 'lead-management/meeting-scheduled',
  LEAD_MANAGEMENT_MEETINGS: 'lead-management/meetings',
  LEAD_MANAGEMENT_CREATE: 'lead-management/create',
  LEAD_MANAGEMENT_EDIT: 'lead-management/edit/:id',
  LEAD_MANAGEMENT_DETAIL: 'lead-management/:id',
  PRE_LEAD_VIEW: 'pre-lead/view',
  PRE_LEAD_CREATE: 'pre-lead/create',
  PRE_LEAD_DETAIL: 'pre-lead/view/:id',
  PRE_LEAD_EDIT: 'pre-lead/view/:id/edit',
  BRIEF: 'brief',
  /** Matches backend permission paths; do not rename without updating permissions. */
  BRIEF_PIPELINE: 'Brief_Pipeline',
  BRIEF_CREATE: 'brief/create',
  BRIEF_LOG: 'brief/log',
  BRIEF_PLAN_HISTORY: 'brief/plan-history/:id',
  BRIEF_PLAN_SUBMISSION: 'brief/plan-submission/:id',
  BRIEF_EDIT_SUBMITTED_PLAN: 'brief/edit-submitted-plan/:id',
  BRIEF_DETAIL: 'brief/:id',
  BRIEF_EDIT: 'brief/:id/edit',
  MEETING: 'meeting',
  MEETING_CREATE: 'meeting/create',
  MEETING_DETAIL: 'meeting/:id',
  MEETING_EDIT: 'meeting/:id/edit',
  USER_MANAGEMENT: 'user-management',
  USER_MANAGEMENT_PERMISSION: 'user-management/permission',
  USER_MANAGEMENT_PERMISSION_CREATE: 'user-management/permission/create',
  USER_MANAGEMENT_PERMISSION_EDIT: 'user-management/permission/edit/:id',
  USER_MANAGEMENT_PERMISSION_DETAIL: 'user-management/permission/:id',
  USER_MANAGEMENT_ROLE: 'user-management/role',
  USER_MANAGEMENT_ROLE_CREATE: 'user-management/role/create',
  USER_MANAGEMENT_ROLE_EDIT: 'user-management/role/edit/:id',
  USER_MANAGEMENT_ROLE_DETAIL: 'user-management/role/:id',
  USER_MANAGEMENT_USER: 'user-management/user',
  USER_MANAGEMENT_USER_CREATE: 'user-management/user/create',
  USER_MANAGEMENT_USER_EDIT: 'user-management/user/edit/:id',
  USER_MANAGEMENT_USER_DETAIL: 'user-management/user/:id',
  MASTER_BRAND: 'master/brand',
  MASTER_BRAND_CREATE: 'master/brand/create',
  MASTER_BRAND_DETAIL: 'master/brand/:id',
  MASTER_BRAND_EDIT: 'master/brand/:id/edit',
  MASTER_BRAND_CONTACTS: 'master/brand/:id/contacts',
  MASTER_AGENCY: 'master/agency',
  MASTER_AGENCY_CREATE: 'master/agency/create',
  MASTER_AGENCY_DETAIL: 'master/agency/:id',
  MASTER_AGENCY_EDIT: 'master/agency/:id/edit',
  MASTER_AGENCY_CONTACTS: 'master/agency/:id/contacts',
  MASTER_INDUSTRY: 'master/industry',
  MASTER_INDUSTRY_CREATE: 'master/industry/create',
  MASTER_INDUSTRY_DETAIL: 'master/industry/:id',
  MASTER_INDUSTRY_EDIT: 'master/industry/:id/edit',
  MASTER_DESIGNATION: 'master/designation',
  MASTER_DESIGNATION_CREATE: 'master/designation/create',
  MASTER_DESIGNATION_DETAIL: 'master/designation/:id',
  MASTER_DESIGNATION_EDIT: 'master/designation/:id/edit',
  MASTER_DEPARTMENT: 'master/department',
  MASTER_DEPARTMENT_CREATE: 'master/department/create',
  MASTER_DEPARTMENT_DETAIL: 'master/department/:id',
  MASTER_DEPARTMENT_EDIT: 'master/department/:id/edit',
  MASTER_SOURCE: 'master/source',
  MASTER_SOURCE_CREATE: 'master/source/create',
  MASTER_SOURCE_DETAIL: 'master/source/:id',
  MASTER_SOURCE_EDIT: 'master/source/:id/edit',
} as const;

const abs = (segment: string) => `/${segment}`;

/** Absolute application paths (leading slash). */
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: abs(ROUTE_SEGMENTS.DASHBOARD),
  DASHBOARD_SALES: abs(ROUTE_SEGMENTS.DASHBOARD_SALES),
  DASHBOARD_PLANNER: abs(ROUTE_SEGMENTS.DASHBOARD_PLANNER),
  COURSES: abs(ROUTE_SEGMENTS.COURSES),
  PROFILE: abs(ROUTE_SEGMENTS.PROFILE),
  SETTINGS: '/settings',
  NOTIFICATIONS: abs(ROUTE_SEGMENTS.NOTIFICATIONS),
  GMAIL: abs(ROUTE_SEGMENTS.GMAIL),
  GMAIL_SEND: abs(ROUTE_SEGMENTS.GMAIL_SEND),
  GMAIL_RECEIVE: abs(ROUTE_SEGMENTS.GMAIL_RECEIVE),
  LEAD_SOURCE: abs(ROUTE_SEGMENTS.LEAD_SOURCE),
  INVENTORY_DEVICE: abs(ROUTE_SEGMENTS.INVENTORY_DEVICE),
  MEETING_SCHEDULE: abs(ROUTE_SEGMENTS.MEETING_SCHEDULE),
  LEAD_MANAGEMENT: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT),
  LEAD: {
    ROOT: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT),
    ALL: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_ALL),
    BRIEF_LEADS: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_BRIEF),
    PENDING: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_PENDING),
    INTERESTED: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_INTERESTED),
    MEETING_SCHEDULED: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_MEETING_SCHEDULED),
    MEETINGS: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_MEETINGS),
    CREATE: abs(ROUTE_SEGMENTS.LEAD_MANAGEMENT_CREATE),
    EDIT: (id: string) => `/lead-management/edit/${id}`,
    DETAIL: (id: string) => `/lead-management/${id}`,
    MEETING_SCHEDULE: abs(ROUTE_SEGMENTS.MEETING_SCHEDULE),
  },
  BRIEF: {
    ROOT: abs(ROUTE_SEGMENTS.BRIEF),
    PIPELINE: `/brief/${ROUTE_SEGMENTS.BRIEF_PIPELINE}`,
    CREATE: abs(ROUTE_SEGMENTS.BRIEF_CREATE),
    LOG: abs(ROUTE_SEGMENTS.BRIEF_LOG),
    PLAN_HISTORY: (id: string) => `/brief/plan-history/${id}`,
    PLAN_SUBMISSION: (id: string) => `/brief/plan-submission/${id}`,
    EDIT_SUBMITTED_PLAN: (id: string) => `/brief/edit-submitted-plan/${id}`,
    EDIT: (id: string) => `/brief/${id}/edit`,
    DETAIL: (id: string) => `/brief/${id}`,
  },
  MISS_CAMPAIGN: {
    ROOT: '/pre-lead',
    VIEW: abs(ROUTE_SEGMENTS.PRE_LEAD_VIEW),
    CREATE: abs(ROUTE_SEGMENTS.PRE_LEAD_CREATE),
    EDIT: (id: string) => `/pre-lead/view/${id}/edit`,
    DETAIL: (id: string) => `/pre-lead/view/${id}`,
  },
  MEETING: {
    ROOT: abs(ROUTE_SEGMENTS.MEETING),
    CREATE: abs(ROUTE_SEGMENTS.MEETING_CREATE),
    DETAIL: (id: string) => `/meeting/${id}`,
    EDIT: (id: string) => `/meeting/${id}/edit`,
  },
  CAMPAIGN_MANAGEMENT: '/campaign-management',
  FINANCE: '/finance',
  USER_MANAGEMENT: abs(ROUTE_SEGMENTS.USER_MANAGEMENT),
  PERMISSION: {
    ROOT: abs(ROUTE_SEGMENTS.USER_MANAGEMENT_PERMISSION),
    CREATE: abs(ROUTE_SEGMENTS.USER_MANAGEMENT_PERMISSION_CREATE),
    EDIT: (id: string) => `/user-management/permission/edit/${id}`,
    DETAIL: (id: string) => `/user-management/permission/${id}`,
  },
  ROLE: {
    ROOT: abs(ROUTE_SEGMENTS.USER_MANAGEMENT_ROLE),
    CREATE: abs(ROUTE_SEGMENTS.USER_MANAGEMENT_ROLE_CREATE),
    EDIT: (id: string) => `/user-management/role/edit/${id}`,
    DETAIL: (id: string) => `/user-management/role/${id}`,
  },
  USER: {
    ROOT: abs(ROUTE_SEGMENTS.USER_MANAGEMENT_USER),
    CREATE: abs(ROUTE_SEGMENTS.USER_MANAGEMENT_USER_CREATE),
    EDIT: (id: string) => `/user-management/user/edit/${id}`,
    DETAIL: (id: string) => `/user-management/user/${id}`,
  },
  BRAND_MASTER: abs(ROUTE_SEGMENTS.MASTER_BRAND),
  BRAND_CONTACTS: (id: string) => `/master/brand/${id}/contacts`,
  AGENCY_MASTER: abs(ROUTE_SEGMENTS.MASTER_AGENCY),
  AGENCY_CONTACTS: (id: string) => `/master/agency/${id}/contacts`,
  DEPARTMENT_MASTER: abs(ROUTE_SEGMENTS.MASTER_DEPARTMENT),
  DESIGNATION_MASTER: abs(ROUTE_SEGMENTS.MASTER_DESIGNATION),
  INDUSTRY_MASTER: abs(ROUTE_SEGMENTS.MASTER_INDUSTRY),
  SOURCE_MASTER: abs(ROUTE_SEGMENTS.MASTER_SOURCE),
} as const;
